### PR TITLE
feat: adding intl-womens-day category

### PR DESCRIPTION
**Pull request by christian14b**
New category for IWD 2024 events

### CODE REVIEW

**Comment by dyersituations** [comment]
Looks good, but I'll wait for approval from @gwilson253

**Review by gwilson253 — APPROVED** [review]
👍

**Comment by mcstover** [comment]
nothing on our side, not sure about on @gwilson253 's side? I think we have to set the config somewhere to push these to amplitude.

**Comment by gwilson253** [comment]
I'll handle everything on the Amplitude side. I usually wait until the events start showing up in Prod to model the data, which is required in order to push the events to Amplitude.

**Pull request merged**
